language: java, node_js

node_js:
  - "8.2.1"

cache:
  directories:
    - "$HOME/.m2"
env:
  - DOCKER_COMPOSE_VERSION=1.25.5

services:
  - docker

install:
  - bash ./travis/install.sh

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
 - bash ./travis/test.sh