language: java, node_js

cache:
  directories:
    - "$HOME/.m2"
env:
  - NET=WSS NETE=WSSE
  - NET=IDSCP NETE=WSSE
  - NET=HTTPS NETE=WSSE
  - NET=WSS NETE=HTTPSE
  - NET=IDSCP NETE=HTTPSE
  - NET=HTTPS NETE=HTTPSE
services:
  - docker

install:
  - bash ./travis/install.sh

before_script:
  - docker ps -a
  - sleep 60 #seconds

script:
  - bash ./travis/test.sh

#after_script:
#    - docker logs market40-execution_core_container_business_logic_data-app_1
#    - docker logs market40-execution_core_container_business_logic_ecc-consumer_1
#    - docker logs market40-execution_core_container_business_logic_ecc-provider_1