language: java, node_js

node_js:
  - "10"

cache:
  directories:
    - "$HOME/.m2"
env:
  - DOCKER_COMPOSE_VERSION=1.25.5

services:
  - docker

install:
  - bash ./travis/install.sh

before_script:
  - node --version
  - npm --version
  - docker ps -a

script:
 - bash ./travis/test.sh

after_script:
  - docker-compose down