language: java, node_js

cache:
  directories:
    - "$HOME/.m2"
env:
  global:
  jobs:
    - NET=WSS NETE=WSSE DAPS=true CH=false
    - NET=WSS NETE=WSSE DAPS=false CH=false
    - NET=WSS NETE=WSSE DAPS=true CH=true
    - NET=WSS NETE=WSSE DAPS=false CH=true

    - NET=IDSCP NETE=WSSE DAPS=true CH=false
    - NET=IDSCP NETE=WSSE DAPS=false CH=false
    - NET=IDSCP NETE=WSSE DAPS=true CH=true
    - NET=IDSCP NETE=WSSE DAPS=false CH=true

    - NET=HTTPS NETE=WSSE DAPS=true CH=false
    - NET=HTTPS NETE=WSSE DAPS=false CH=false
    - NET=HTTPS NETE=WSSE DAPS=true CH=true
    - NET=HTTPS NETE=WSSE DAPS=false CH=true

    - NET=WSS NETE=HTTPSE DAPS=true CH=false
    - NET=WSS NETE=HTTPSE DAPS=false CH=false
    - NET=WSS NETE=HTTPSE DAPS=true CH=true
    - NET=WSS NETE=HTTPSE DAPS=false CH=true

    - NET=IDSCP NETE=HTTPSE DAPS=true CH=false
    - NET=IDSCP NETE=HTTPSE DAPS=false CH=false
    - NET=IDSCP NETE=HTTPSE DAPS=true CH=true
    - NET=IDSCP NETE=HTTPSE DAPS=false CH=true

    - NET=HTTPS NETE=HTTPSE DAPS=true CH=false
    - NET=HTTPS NETE=HTTPSE DAPS=false CH=false
    - NET=HTTPS NETE=HTTPSE DAPS=true CH=true
    - NET=HTTPS NETE=HTTPSE DAPS=false CH=true

services:
  - docker

install:  # Data-app branch name optional ex. install.sh develop
  - bash ./travis/install.sh

before_script:
  - docker ps -a
  - sleep 60 #seconds

script:
  - bash ./travis/test.sh

after_script:
  - docker logs docker_data-app_1
  - docker logs docker_ecc-provider_1
  - docker logs docker_ecc-consumer_1

jobs:
  include:
    - stage: deploy
      # Deploy in DockerHub
      script: echo Deploy
      env: NET=HTTPS NETE=HTTPSE DAPS=false CH=true