language: java, node_js

cache:
  directories:
    - "$HOME/.m2"
env:
  - NET=WSS NET-E=WSSE DAPS=true CH=false
  - NET=WSS NET-E=WSSE DAPS=false CH=false
  - NET=WSS NET-E=WSSE DAPS=true CH=true
  - NET=WSS NET-E=WSSE DAPS=false CH=true

  - NET=IDSCP NET-E=WSSE DAPS=true CH=false
  - NET=IDSCP NET-E=WSSE DAPS=false CH=false
  - NET=IDSCP NET-E=WSSE DAPS=true CH=true
  - NET=IDSCP NET-E=WSSE DAPS=false CH=true

  - NET=HTTPS NET-E=WSSE DAPS=true CH=false
  - NET=HTTPS NET-E=WSSE DAPS=false CH=false
  - NET=HTTPS NET-E=WSSE DAPS=true CH=true
  - NET=HTTPS NET-E=WSSE DAPS=false CH=true

  - NET=WSS NET-E=HTTPSE DAPS=true CH=false
  - NET=WSS NET-E=HTTPSE DAPS=false CH=false
  - NET=WSS NET-E=HTTPSE DAPS=true CH=true
  - NET=WSS NET-E=HTTPSE DAPS=false CH=true

  - NET=IDSCP NET-E=HTTPSE DAPS=true CH=false
  - NET=IDSCP NET-E=HTTPSE DAPS=false CH=false
  - NET=IDSCP NET-E=HTTPSE DAPS=true CH=true
  - NET=IDSCP NET-E=HTTPSE DAPS=false CH=true

  - NET=HTTPS NET-E=HTTPSE DAPS=true CH=false
  - NET=HTTPS NET-E=HTTPSE DAPS=false CH=false
  - NET=HTTPS NET-E=HTTPSE DAPS=true CH=true
  - NET=HTTPS NET-E=HTTPSE DAPS=false CH=true

services:
  - docker

install:  # Data-app branch name optional ex. install.sh develop
  - bash ./travis/install.sh

before_script:
  - docker ps -a
  - sleep 60 #seconds

script:
  - bash ./travis/test.sh

#after_script:
#    - docker logs market40-execution_core_container_business_logic_data-app_1
#    - docker logs market40-execution_core_container_business_logic_ecc-consumer_1
#    - docker logs market40-execution_core_container_business_logic_ecc-provider_1