language: java, node_js

cache:
  directories:
    - "$HOME/.m2"
env:
  - DOCKER_COMPOSE_VERSION=1.25.5

services:
  - docker

install:
  - bash ./travis/install.sh


#script:
#  - bash ./travis/test.sh