language: java, node_js

node_js:
  - "10"

cache:
  directories:
    - "$HOME/.m2"
env:
  - DOCKER_COMPOSE_VERSION=1.25.5

services:
  - docker

install:
  - bash ./travis/install.sh

before_script:
  - docker ps -a
  - sleep 60

script:
 - bash ./travis/test.sh

after_script:
  - docker logs  market40-execution_core_container_business_logic_data-app_1
  - docker-compose down