language: java, node_js
cache:
  directories:
  - "$HOME/.m2"
env:
  matrix:
  - NET=WSS NETE=WSSE DAPS=true CH=false
  - NET=WSS NETE=WSSE DAPS=false CH=false
  - NET=WSS NETE=WSSE DAPS=true CH=true
  - NET=WSS NETE=WSSE DAPS=false CH=true
  - NET=IDSCP NETE=WSSE DAPS=true CH=false
  - NET=IDSCP NETE=WSSE DAPS=false CH=false
  - NET=IDSCP NETE=WSSE DAPS=true CH=true
  - NET=IDSCP NETE=WSSE DAPS=false CH=true
  - NET=HTTPS NETE=WSSE DAPS=true CH=false
  - NET=HTTPS NETE=WSSE DAPS=false CH=false
  - NET=HTTPS NETE=WSSE DAPS=true CH=true
  - NET=HTTPS NETE=WSSE DAPS=false CH=true
  - NET=WSS NETE=HTTPSE DAPS=true CH=false
  - NET=WSS NETE=HTTPSE DAPS=false CH=false
  - NET=WSS NETE=HTTPSE DAPS=true CH=true
  - NET=WSS NETE=HTTPSE DAPS=false CH=true
  - NET=IDSCP NETE=HTTPSE DAPS=true CH=false
  - NET=IDSCP NETE=HTTPSE DAPS=false CH=false
  - NET=IDSCP NETE=HTTPSE DAPS=true CH=true
  - NET=IDSCP NETE=HTTPSE DAPS=false CH=true
  - NET=HTTPS NETE=HTTPSE DAPS=true CH=false
  - NET=HTTPS NETE=HTTPSE DAPS=false CH=false
  - NET=HTTPS NETE=HTTPSE DAPS=true CH=true
  - NET=HTTPS NETE=HTTPSE DAPS=false CH=true
  global:
  - secure: K3i0j0PILpZ2iSocwBQStRxYwbnlGsJdJ2ZZHBIY61S0hcdwLmLchzlazOpIEmHbGPSiw48HC899BCcmsUXKJciHtWdskNnC3YLKhZFVd7ehn6KKC4kofNkCywkfQ+o9kKwlLkGd3aheKbi6mRT79rtiSk6b4F0nA3blDJ+2huf85Xy7OOYu+AhT/X2OokjXVzOrq7C9g7iYA80nyZrBqjkswIZ6pE8hlNEOCR42gApb06hopZXqPUKDxGO5H1N5bV4w0I8HZLkRl9yNwk0UfP97s/VmKyO15xvBMNMtUknbigkJvrA88iwUJUNfCrmLoxQM0J/vllATLc9SxpFjs1eOvv09rwEQq+Bv5Mgy+zuEmZECs2o77kPm9lhnVGndAIPxK3X9D5Yg2rzseLAOZizx27sWrvgt+XEe4cI9w3uR0T16WNCqXlI3jtIZHg8X3BTCesVjlVy6zrH01bC9n0yrv75Th4m2X9kokskbvnw6/CIn9+z80G9vXM00DWkIAGdvDTanZVHy0/g/1KOrruYf05FByBehmWOcA7y4lDtAV8iMPunByk9K2/WToF25cGKTddCerLxyyeisQZ7YoUCoET6rcEheQSwRMZZEgn6ZyjDB2gy9VWccq7ISrcya5Z8WKbA3IAGr/lsRG3b3qhLGJRx2T9EbJs48YsPxlc4=
  - secure: kJsDkI8Pb0UNHHoh1l7F4vZwwIsGeZyuplkWax06dH1WG917nE48y33W+GiQw/bjK2LLQDU//2S1BDsU6MxLMxqUJNtQegI6iAXCnwKGAqq4uaC/CqC4mVEZibiCsN/9SdJM6RUUUor6vY16DnQV+MrCnaLHWhD+L21nYu1Ryzzd6gaXNhu3XtIk+jE8iTxTHucju6e09dSk33m0O8PolNrJwV8IqF0ADZ+vpqeuTJ0YMAbwa95F/LNiZFQ7udTK93KnCW2O/60hskNW8G3+7+WnX9DrXbPAjwVQr7u5T2CkmBQHNr0J5F4WjSTWM9phNbRrqRes2r5PVmnesZwWqqePe9eeFJZ6gnoZA5qBqZNyrUfkcwKH+hPHSMIkbz3FX11Bro69uxwUO3lQ9/nt/NaEUwKh+0QIQns8rBVcwBbFy/5cAju+JbJ2uxfPOHItqrKlHCh0YJsPZDrz1cfl+3X6sn32hwBq6z0AL7HebkW2t9iUlelfegAtz0nN5ksKLZrg8pFxVCkrC/vRfhpF5d2nlIcbnkyJZ03Axm2c+wOLwcwfyKuWS1By4YaATDxeBk1D2cvE0dhRbj+VU69uDwhvqwTEvbdxxYXt+8iR5X278hPxftmXoBEY8JDheq9WNSlaXCQ3DeIFkBC7XGc7ABmC2djMihLGc+BtKULwq94=
services:
- docker
install:
- bash ./travis/install.sh
before_script:
- docker ps -a
- sleep 60
script:
- bash ./travis/test.sh
after_script:
- docker logs docker_data-app_1
- docker logs docker_ecc-provider_1
- docker logs docker_ecc-consumer_1
jobs:
  include:
  - stage: deploy
    script: echo Deploy
    env: NET=WSS NETE=WSSE DAPS=true CH=false
